### ISSUE TITLE
Restrict Twitch live announcements to a selection of games

### ISSUE THREAD

**Issue by marysiamzawka** [MattTheDev/CouchBot#109]
An ability for the bot to only announce streams of an user-defined list of games would be nifty for game-series related Discord servers.

**Comment by MattTheDev** [comment]
Hi there friend!!

http://docs.couch.bot/en/latest/gameandtitlefilters.html

Ask and you shall receive! :)  Leaving this open until you can confirm / close it.

If you need some help, http://discord.couch.bot.

**Comment by marysiamzawka** [comment]
Can confirm I'm blind. Huge thanks yo
