### ISSUE TITLE
Clickable preview image

### ISSUE THREAD

**Issue by tommerty** [MattTheDev/CouchBot#119]
This is my first ever time using Github, so I'm sorry if I do anything wrong when creating this.

On the embed of the stream on Discord, when you click the preview image, it would be cool if the image was also an embedded link that would directly send you to the stream. (I've had a few not-so-smart people telling me the bot wasn't working, and they were clicking the image, not the link)

**Comment by JaymeiF** [comment]
Unfortunately the image itself is sourced from the streaming platform link.
e.g https://thumb-us-west1.picarto.tv/thumbnail/rtil.jpg would return the stream preview image for rtil on Picarto

tl;dr
The image is a link to the picture itself, without it there would be no image.

**Comment by tommerty** [comment]
Aye, I fully understand! No problem, thanks for clarification!
