### ISSUE TITLE
Suggestion for `greetings` and `goodbyes`

### ISSUE THREAD

**Issue by SUPERCHIEFYT** [MattTheDev/CouchBot#122]
`USERNAME` - Only displays their username (i.e: `SUPERCHIEFYT`)
`USERTAG` - Only displays their username#disciminator (i.e: `SUPERCHIEFYT#0001`)

Currently there is `%USER%` which only displays if the user is in your cache, or `%NICKNAME%` but that can't display their full-name only.

**Comment by MattTheDev** [comment]
Local tests successful. Will be deployed tonight.
