### ISSUE TITLE
Make sure all commands are listed in the Wiki.

### ISSUE THREAD

**Issue by MattTheDev** [MattTheDev/CouchBot#37]

**Comment by dawgeth** [comment]
Missing these...

* !cb mixer status
* !cb purge [@someone] [count]
* !cb purgeall
* !cb flip
* !cb unflip
* !cb echo "string"
* !cb echoembed "string"
* !cb ping
* !cb servers
* !cb permissions #DiscordChannelName
* !cb message live/published clear
* !cb help "question"
* !cb twitch discover [all/none/role] {roleName}
* !cb twitch live
* !cb allow all true/false
* !cb config mentionrole here
* !cb allow mention [platform] [type] [true/false]
