### ISSUE TITLE
[Beam Enhancement] Configuration item to allow for Mixer announcements to be ignored if within X amount of time.

### ISSUE THREAD

**Issue by Emcipio** [MattTheDev/CouchBot#38]
Couchbot is working properly in this case, but it's getting annoying: For users who cut their stream and go live frequently within a few minutes of each stream, i.e. mobile streamers, could you add a command to disable repeating messages from the same streamer source within a certain time period? For example, allowing a command to disable alerts from a single source within an hour would be great for someone who owns a server and wants to cut down on promotional spam.

**Comment by dawgeth** [comment]
Have you tried turning on the deletion of messages when a user goes offline? 

Used to have a delay in there where cleanup would happen every 60 minutes - but people wanted it lower, for folks that .. go offline/online in a short amount of time.. haha.

I've got a BIG overhaul of the data storage being worked on now ... I will have date/time when something goes live. I could probably work this into that.

What platform are you using?

**Comment by Emcipio** [comment]
I'm a Mixer only streamer, and it's come to my attention that mobile Mixer streamers commonly will lock their phones when something comes up and they have to direct attention away from the stream. I use Discord and Mixer on PC.

**Comment by dawgeth** [comment]
Ah ok, I can see why that'd happen. Mixer is the only one with INSTANT notifications and this is why you guys get beat up. 

Ill see what I can do ;)

**Comment by Emcipio** [comment]
Any new progress on this issue?
