### ISSUE TITLE
Allow YT live announce footer to properly display www.youtube text & image

### ISSUE THREAD

**Issue by DGX-Development** [MattTheDev/CouchBot#45]
On live announce footers, gaming.youtube and the YTG icon are shown regardless if the YTG URLS For VOD Content is set to False. This feature works partially correctly for published announcements (says YouTUbe but shows YTG icon) but not live content.

If this is not a bug but a limitation of API or other reason, please close. It was suggested in the couchbot discord I post this here.

Images for comparison at: https://ibb.co/e94Eev and https://ibb.co/mpmhXF 
![1](https://user-images.githubusercontent.com/30995201/29258610-abce4bdc-8080-11e7-8615-875af6854451.png)
![2](https://user-images.githubusercontent.com/30995201/29258611-abcf22dc-8080-11e7-84d8-5dec89f5bff9.png)

**Comment by dawgeth** [comment]
I'll get this fixed! thanks for letting me know :)
