### ISSUE TITLE
Twitch Channel Feed Issue - Not posting seemingly when announced from Dashboard.

### ISSUE THREAD

**Issue by MattTheDev** [MattTheDev/CouchBot#63]
8:46 PM] santa2452: Just an update on the intermittent issue with my channel feed,  I posted an update through the twitch app and it seemed to be announced, so far the only time I notice it not being announced was when I did it through the dashboard. I may be able to test that later tonight before I go live.

**Comment by InsaneFirebat** [comment]
From santa2452
> I dont have a github account, but I just tested the dashboard theory, here is a picture (if it will help). C for channel update, D for dashboard, App for the twitch app.

![cb-dashboard_test](https://user-images.githubusercontent.com/7481498/32208376-8abfd56a-bdd8-11e7-8ba8-3c079e419a66.PNG)
