### ISSUE TITLE
CB is crossposting.. an shouldnt be #CantFixIt

### ISSUE THREAD

**Issue by LadyAnailaigh** [MattTheDev/CouchBot#66]
Either im dumb or i cant find it... i honestly think its a bug
if its not KINDLY point me to the area where i can fix my 
issue. thanks

Issue:

setup 2 different channels for livestreams/vids and unfortunately
it seems that despite different ppl in both (as in no one from group
1 is listed in group 2 & vice versa) its cross posting >_< i cant have
it crost post. I need it to keep all the 1 set of folks in the one channel
an the other set in the other.

Please help!

Thanks

**Comment by LadyAnailaigh** [comment]
hello?

**Comment by dawgeth** [comment]
I flagged this on a sticky note .. and forgot to look!! I am VERY sorry.

The only way to get the bot to post to 2 different channels is ...

Live vs. Published

or Owner vs. Others..

Can you do:

!cb config list
and
!cb streamer list 

and post the results here? Also - the bot is going premium after tonight. As a heads up :( Been reaching out to all owner I can.
