### ISSUE TITLE
"config list misc" doesn't await a task

### ISSUE THREAD

**Issue by nozzlegear** [MattTheDev/CouchBot#70]
**Describe the bug**
Hello, we're using CouchBot in our guild Discord and discovered that running `!cb config list misc` only returns "System.Threading.Tasks.Task..." instead of whatever should be in the body. It seems the program isn't awaiting a task and the task itself is being stringified instead.

**To Reproduce**
1. Type `!cb config list misc`
2. Result will say something along the lines of 
```
GUILD NAME Configuration Settings
System.Threading.Tasks.Task`1[System.String]
```

**Expected behavior**
CouchBot should show the configuration list.

**Screenshots**

![image](https://user-images.githubusercontent.com/2417276/47927639-e0ec3200-de91-11e8-8e42-254554910484.png)

**Additional context**
Normally I'd open a pull request for something like this, but I can't for the life of me figure out which class handles the `Config` group.

**Comment by nozzlegear** [comment]
Thanks! I wasn't aware we were on an older version, I'll talk to the guild owner about updating it.

**Comment by MattTheDev** [comment]
This has been resolved and deployed :)

**Comment by nozzlegear** [comment]
Confirmed working for us, thanks for the fix!
