### ISSUE TITLE
Suggestion about Embeds

### ISSUE THREAD

**Issue by JGriffin34432** [MattTheDev/CouchBot#76]
**Is your feature request related to a problem? Please describe.**

My feature request is not related to a problem.

**Describe the solution you'd like**

Add transparent logos of the platform at the bottom of the embed.

**Describe alternatives you've considered**

There isn't any other alternatives.

**Additional context**

![image](https://user-images.githubusercontent.com/32964555/54639059-dd350280-4a62-11e9-83e7-586458f0cbb3.png)

**Comment by MattTheDev** [comment]
Should be good to go. Better late than never.. I hope..?! :(
